name: strf3.9
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9

  # Core scientific stack
  - numpy
  - scipy
  - pandas
  - matplotlib
  - sympy

  # Jupyter / IPython
  - ipython
  - ipykernel
  - jupyter_client
  - jupyter_core

  # Utilities
  - pytest
  - setuptools
  - pip

  - pip:
      - cython
      - soundfile
      - tables
      - thorns
